name = "ATmega6450P"
alias = "m6450p"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x96", "0x0e",]
jtagid = "0x0960E03F"
interfaces = [ "isp", "hvpp", "jtag",]
pagesize = 256

[addresses]
sram = 4096
flash = 65536
eeprom = 2048
