name = "ATmega325"
alias = "m325"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x95", "0x05",]
jtagid = "0x0950503F"
interfaces = [ "isp", "hvpp", "jtag",]

[addresses]
sram = 2048
flash = 32768
eeprom = 1024
