name = "ATmega1280"
alias = "m1280"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x97", "0x03",]
jtagid = "0x0970303F"
interfaces = [ "isp", "hvpp", "jtag",]

[addresses]
sram = 8192
flash = 131072
eeprom = 4096
