name = "ATmega645"
alias = "m645"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x96", "0x05",]
jtagid = "0x0960503F"
interfaces = [ "isp", "hvpp", "jtag",]
pagesize = 256

[addresses]
sram = 4096
flash = 65536
eeprom = 2048
