name = "ATmega3290P"
alias = "m3290p"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x95", "0x0c",]
jtagid = "0x0950C03F"
interfaces = [ "isp", "hvpp", "jtag",]
pagesize = 128

[addresses]
sram = 2048
flash = 32768
eeprom = 1024
