name = "ATmega8515"
alias = "m8515"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x93", "0x06",]
interfaces = [ "isp", "hvpp",]
pagesize = 64

[addresses]
sram = 512
flash = 8192
eeprom = 512
