name = "ATmega64"
alias = "m64"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x96", "0x02",]
jtagid = "0x0960203F"
interfaces = [ "isp", "hvpp", "jtag",]

[addresses]
sram = 4096
flash = 65536
eeprom = 2048
