name = "ATmega32"
alias = "m32"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x95", "0x02",]
jtagid = "0x0950203F"
interfaces = [ "isp", "hvpp", "jtag",]

[addresses]
sram = 2048
flash = 32768
eeprom = 1024
