name = "ATmega324PA"
alias = "m324pa"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x95", "0x11",]
jtagid = "0x0951103F"
interfaces = [ "isp", "hvpp", "jtag",]
pagesize = 128

[addresses]
sram = 2048
flash = 32768
eeprom = 1024
