name = "ATmega164P"
alias = "m164p"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x94", "0x0a",]
jtagid = "0x0940a03F"
interfaces = [ "isp", "hvpp", "jtag",]

[addresses]
sram = 1024
flash = 16384
eeprom = 512
