name = "ATmega165A"
alias = "m165a"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x94", "0x10",]
jtagid = "0x0940703F"
interfaces = [ "isp", "hvpp", "jtag",]

[addresses]
sram = 1024
flash = 16384
eeprom = 512
