name = "ATmega16HVB"
alias = "m16hvb"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x94", "0x0d",]
interfaces = [ "isp", "hvpp", "dw",]
pagesize = 128

[addresses]
sram = 1024
flash = 16384
eeprom = 512
