name = "ATmega168A"
alias = "m168a"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x94", "0x06",]
interfaces = [ "isp", "hvpp", "dw",]
pagesize = 128

[addresses]
sram = 1024
flash = 16384
eeprom = 512
