name = "ATmega162"
alias = "m162"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x94", "0x04",]
jtagid = "0x0940403F"
interfaces = [ "isp", "hvpp", "jtag",]
pagesize = 128

[addresses]
sram = 1024
flash = 16384
eeprom = 512
