name = "ATmega649"
alias = "m649"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x96", "0x03",]
jtagid = "0x0960303F"
interfaces = [ "isp", "hvpp", "jtag",]

[addresses]
sram = 4096
flash = 65536
eeprom = 2048
