name = "ATmega645P"
alias = "m645p"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x96", "0x0D",]
jtagid = "0x0960D03F"
interfaces = [ "isp", "hvpp", "jtag",]

[addresses]
sram = 4096
flash = 65536
eeprom = 2048
