name = "ATmega644PA"
alias = "m644pa"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x96", "0x0a",]
jtagid = "0x0960A03f"
interfaces = [ "isp", "hvpp", "jtag",]

[addresses]
sram = 4096
flash = 65536
eeprom = 2048
