name = "ATmega325A"
alias = "m325a"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x95", "0x05",]
jtagid = "0x0950D03F"
interfaces = [ "isp", "hvpp", "jtag",]
pagesize = 128

[addresses]
sram = 2048
flash = 32768
eeprom = 1024
