name = "ATmega6490"
alias = "m6490"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x96", "0x04",]
jtagid = "0x0960403F"
interfaces = [ "isp", "hvpp", "jtag",]

[addresses]
sram = 4096
flash = 65536
eeprom = 2048
