name = "ATmega324P"
alias = "m324p"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x95", "0x08",]
jtagid = "0x0950803F"
interfaces = [ "isp", "hvpp", "jtag",]
pagesize = 128

[addresses]
sram = 2048
flash = 32768
eeprom = 1024
