name = "ATmega3290"
alias = "m3290"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x95", "0x04",]
jtagid = "0x0950403F"
interfaces = [ "isp", "hvpp", "jtag",]

[addresses]
sram = 2048
flash = 32768
eeprom = 1024
