name = "ATmega64M1"
alias = "m64m1"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x96", "0x84",]
interfaces = [ "isp", "hvpp", "dw",]
pagesize = 256

[addresses]
sram = 4096
flash = 65536
eeprom = 2048
