name = "ATmega329P"
alias = "m329p"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x95", "0x0b",]
jtagid = "0x0950B03F"
interfaces = [ "isp", "hvpp", "jtag",]

[addresses]
sram = 2048
flash = 32768
eeprom = 1024
