name = "ATmega16"
alias = "m16"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x94", "0x03",]
jtagid = "0x0940303F"
interfaces = [ "isp", "hvpp", "jtag",]
pagesize = 128

[addresses]
sram = 1024
flash = 16384
eeprom = 512
