name = "ATmega32C1"
alias = "m32c1"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x95", "0x86",]
interfaces = [ "isp", "hvpp", "dw",]
pagesize = 128

[addresses]
sram = 2048
flash = 32768
eeprom = 1024
