name = "ATmega168PA"
alias = "m168pa"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x94", "0x0b",]
interfaces = [ "isp", "hvpp", "dw",]
pagesize = 128

[addresses]
sram = 1024
flash = 16384
eeprom = 512
