name = "ATmega6490P"
alias = "m6490p"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x96", "0x0C",]
jtagid = "0x0960C03F"
interfaces = [ "isp", "hvpp", "jtag",]

[addresses]
sram = 4096
flash = 65536
eeprom = 2048
