name = "ATmega6450"
alias = "m6450"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x96", "0x06",]
jtagid = "0x0960603F"
interfaces = [ "isp", "hvpp", "jtag",]

[addresses]
sram = 4096
flash = 65536
eeprom = 2048
