name = "ATmega3250"
alias = "m3250"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x95", "0x06",]
jtagid = "0x0950603F"
interfaces = [ "isp", "hvpp", "jtag",]

[addresses]
sram = 2048
flash = 32768
eeprom = 1024
