name = "ATmega48"
alias = "m48"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x92", "0x05",]
interfaces = [ "isp", "hvpp", "dw",]
pagesize = 64

[addresses]
sram = 512
flash = 4096
eeprom = 256
