name = "ATmega169PA"
alias = "m169pa"
arch = "AVR8"
family = "megaAVR"
signatures = [ "0x1e", "0x94", "0x05",]
jtagid = "0x0940503F"
interfaces = [ "isp", "hvpp", "jtag",]

[addresses]
sram = 1024
flash = 16384
eeprom = 512
