name = "ATtiny87"
alias = "t87"
arch = "AVR8"
family = "tinyAVR"
signatures = [ "0x1e", "0x93", "0x87",]
interfaces = [ "isp", "hvpp", "dw",]
pagesize = 128

[addresses]
sram = 512
flash = 8192
eeprom = 512
