name = "ATtiny261A"
alias = "t261a"
arch = "AVR8"
family = "tinyAVR"
signatures = [ "0x1e", "0x91", "0x0c",]
interfaces = [ "isp", "hvpp", "dw",]
pagesize = 32

[addresses]
sram = 128
flash = 2048
eeprom = 128
