name = "ATtiny44A"
alias = "t44a"
arch = "AVR8"
family = "tinyAVR"
signatures = [ "0x1e", "0x92", "0x07",]
interfaces = [ "isp", "hvsp", "dw",]
pagesize = 64

[addresses]
sram = 256
flash = 4096
eeprom = 256
