name = "ATtiny828"
alias = "t828"
arch = "AVR8"
family = "tinyAVR"
signatures = [ "0x1e", "0x93", "0x14",]
interfaces = [ "isp", "hvpp", "dw",]
pagesize = 64

[addresses]
sram = 512
flash = 8192
eeprom = 256
