name = "ATtiny461"
alias = "t461"
arch = "AVR8"
family = "tinyAVR"
signatures = [ "0x1e", "0x92", "0x08",]
interfaces = [ "isp", "hvpp", "dw",]
pagesize = 64

[addresses]
sram = 256
flash = 4096
eeprom = 256
