name = "ATtiny84"
alias = "t84"
arch = "AVR8"
family = "tinyAVR"
signatures = [ "0x1e", "0x93", "0x0c",]
interfaces = [ "isp", "hvsp", "dw",]
pagesize = 64

[addresses]
sram = 512
flash = 8192
eeprom = 512
