name: ATPRsup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NAME: atprsup
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: 'Cache: Rust'
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo
          ./target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: 'Linux: Install dependencies'
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get install pkg-config libusb-dev libusb-1.0

    - name: 'Windows: Install dependencies'
      if: ${{ runner.os == 'Windows' }}
      run: |
        vcpkg integrate install
        vcpkg install libusb:x64-windows-static
        echo "LIBUSB_DIR=C:/vcpkg/installed/x64-windows-static/" | Out-File -FilePath $Env:GITHUB_ENV -Encoding UTF-8 -Append

    - name: 'Cache: vcpkg'
      if: ${{ runner.os == 'Windows' }}
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}
        path: $VCPKG_DIRECTORY

    - name: Build
      run: cargo build --verbose --release

    - name: Run tests
      run: cargo test --verbose

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.NAME }}-${{ runner.os }}-${{ github.run_number }}
        path: target/release/${{ env.NAME }}
